[tool.poetry]
name = "task-5-1"
version = "0.1.0"
description = ""
authors = ["flam7060 <Chal0v-Danil@ya.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
sympy = "^1.13.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
